//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config4GDeployment) DeepCopyInto(out *Config4GDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config4GDeployment.
func (in *Config4GDeployment) DeepCopy() *Config4GDeployment {
	if in == nil {
		return nil
	}
	out := new(Config4GDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config4GDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config4GDeploymentList) DeepCopyInto(out *Config4GDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Config4GDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config4GDeploymentList.
func (in *Config4GDeploymentList) DeepCopy() *Config4GDeploymentList {
	if in == nil {
		return nil
	}
	out := new(Config4GDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config4GDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config4GDeploymentSpec) DeepCopyInto(out *Config4GDeploymentSpec) {
	*out = *in
	in.NFDeploymentSpec.DeepCopyInto(&out.NFDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config4GDeploymentSpec.
func (in *Config4GDeploymentSpec) DeepCopy() *Config4GDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(Config4GDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config4GDeploymentStatus) DeepCopyInto(out *Config4GDeploymentStatus) {
	*out = *in
	in.NFDeploymentStatus.DeepCopyInto(&out.NFDeploymentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config4GDeploymentStatus.
func (in *Config4GDeploymentStatus) DeepCopy() *Config4GDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(Config4GDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSSDeployment) DeepCopyInto(out *HSSDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSSDeployment.
func (in *HSSDeployment) DeepCopy() *HSSDeployment {
	if in == nil {
		return nil
	}
	out := new(HSSDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HSSDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSSDeploymentList) DeepCopyInto(out *HSSDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HSSDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSSDeploymentList.
func (in *HSSDeploymentList) DeepCopy() *HSSDeploymentList {
	if in == nil {
		return nil
	}
	out := new(HSSDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HSSDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSSDeploymentSpec) DeepCopyInto(out *HSSDeploymentSpec) {
	*out = *in
	in.NFDeploymentSpec.DeepCopyInto(&out.NFDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSSDeploymentSpec.
func (in *HSSDeploymentSpec) DeepCopy() *HSSDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(HSSDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSSDeploymentStatus) DeepCopyInto(out *HSSDeploymentStatus) {
	*out = *in
	in.NFDeploymentStatus.DeepCopyInto(&out.NFDeploymentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSSDeploymentStatus.
func (in *HSSDeploymentStatus) DeepCopy() *HSSDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(HSSDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MMEDeployment) DeepCopyInto(out *MMEDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MMEDeployment.
func (in *MMEDeployment) DeepCopy() *MMEDeployment {
	if in == nil {
		return nil
	}
	out := new(MMEDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MMEDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MMEDeploymentList) DeepCopyInto(out *MMEDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MMEDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MMEDeploymentList.
func (in *MMEDeploymentList) DeepCopy() *MMEDeploymentList {
	if in == nil {
		return nil
	}
	out := new(MMEDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MMEDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MMEDeploymentSpec) DeepCopyInto(out *MMEDeploymentSpec) {
	*out = *in
	in.NFDeploymentSpec.DeepCopyInto(&out.NFDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MMEDeploymentSpec.
func (in *MMEDeploymentSpec) DeepCopy() *MMEDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(MMEDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MMEDeploymentStatus) DeepCopyInto(out *MMEDeploymentStatus) {
	*out = *in
	in.NFDeploymentStatus.DeepCopyInto(&out.NFDeploymentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MMEDeploymentStatus.
func (in *MMEDeploymentStatus) DeepCopy() *MMEDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(MMEDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCRFDeployment) DeepCopyInto(out *PCRFDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCRFDeployment.
func (in *PCRFDeployment) DeepCopy() *PCRFDeployment {
	if in == nil {
		return nil
	}
	out := new(PCRFDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PCRFDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCRFDeploymentList) DeepCopyInto(out *PCRFDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PCRFDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCRFDeploymentList.
func (in *PCRFDeploymentList) DeepCopy() *PCRFDeploymentList {
	if in == nil {
		return nil
	}
	out := new(PCRFDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PCRFDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCRFDeploymentSpec) DeepCopyInto(out *PCRFDeploymentSpec) {
	*out = *in
	in.NFDeploymentSpec.DeepCopyInto(&out.NFDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCRFDeploymentSpec.
func (in *PCRFDeploymentSpec) DeepCopy() *PCRFDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(PCRFDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCRFDeploymentStatus) DeepCopyInto(out *PCRFDeploymentStatus) {
	*out = *in
	in.NFDeploymentStatus.DeepCopyInto(&out.NFDeploymentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCRFDeploymentStatus.
func (in *PCRFDeploymentStatus) DeepCopy() *PCRFDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(PCRFDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SPGWCDeployment) DeepCopyInto(out *SPGWCDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SPGWCDeployment.
func (in *SPGWCDeployment) DeepCopy() *SPGWCDeployment {
	if in == nil {
		return nil
	}
	out := new(SPGWCDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SPGWCDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SPGWCDeploymentList) DeepCopyInto(out *SPGWCDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SPGWCDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SPGWCDeploymentList.
func (in *SPGWCDeploymentList) DeepCopy() *SPGWCDeploymentList {
	if in == nil {
		return nil
	}
	out := new(SPGWCDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SPGWCDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SPGWCDeploymentSpec) DeepCopyInto(out *SPGWCDeploymentSpec) {
	*out = *in
	in.NFDeploymentSpec.DeepCopyInto(&out.NFDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SPGWCDeploymentSpec.
func (in *SPGWCDeploymentSpec) DeepCopy() *SPGWCDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(SPGWCDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SPGWCDeploymentStatus) DeepCopyInto(out *SPGWCDeploymentStatus) {
	*out = *in
	in.NFDeploymentStatus.DeepCopyInto(&out.NFDeploymentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SPGWCDeploymentStatus.
func (in *SPGWCDeploymentStatus) DeepCopy() *SPGWCDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(SPGWCDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
